[package]
name = "evcxr_jupyter"
version = "0.5.3"
license = "Apache-2.0"
description = "An Jupyter Kernel for Rust"
repository = "https://github.com/google/evcxr"
readme = "README.md"
authors = [
    "David Lattimore <dvdlttmr@gmail.com>",
    "David Bernard <david.bernard.31@gmail.com>",
]
edition = "2018"

[dependencies]
evcxr = { version = "=0.5.3", path = "../evcxr" }
json = "0.11.15"
anyhow = "1.0.33"
zmq = { version = "0.9.1", default-features = false }
uuid = { version = "0.7.4", features = [ "v4" ] }
hmac = "0.7.1"
sha2 = "0.8.0"
hex = "0.3.2"
colored = "1.8.0"
dirs = "2.0.2"
chrono = "0.4.7"
unicode-segmentation = "1.6.0"

[features]
default = ["vendored-zmq"]
vendored-zmq = ["zmq/vendored"]
