[package]
name = "evcxr"
version = "0.5.3"
license = "Apache-2.0"
description = "An Evaluation Context for Rust"
repository = "https://github.com/google/evcxr"
readme = "README.md"
authors = [
    "David Lattimore <dvdlttmr@gmail.com>",
    "Matthias Bussonnier <bussonniermatthias@gmail.com>",
    "Daniel Griffen <daniel@griffen.io>",
    "David Bernard <david.bernard.31@gmail.com>",
]
edition = "2018"

[dependencies]
# TODO: Migrate off of syn and proc-macro2 and use rust-analyzer where needed.
syn = { version = "1.0.11", default-features = false, features = ["parsing", "full", "printing", "clone-impls", "extra-traits", "visit"] }
proc-macro2 = { version = "1.0.6", default-features = false }
# TODO: Consider using anyhow more widely, or at least getting rid of our use of the failure crate.
anyhow = "1.0.33"
failure = { version = "0.1.5", default-features = false, features = [ "std" ] }
tempfile = "3.1.0"
libc = "0.2.62"
json = "0.11.15"
regex = { version = "1.3.1", default-features = false, features = [ "std" ] }
lazy_static = "1.3.0"
libloading = "0.5.2"
backtrace = "0.3.35"
dirs = "2.0.2"
which = "2.0.1"
evcxr_input = "1.0.0"
ra_ap_ide = "=0.0.19"
ra_ap_project_model = "=0.0.19"
ra_ap_paths = "=0.0.19"
ra_ap_vfs = "=0.0.19"
ra_ap_vfs-notify = "=0.0.19"
ra_ap_hir = "=0.0.19"
ra_ap_base_db = "=0.0.19"
ra_ap_syntax = "=0.0.19"

[target.'cfg(all(unix, not(target_os = "freebsd")))'.dependencies]
sig = "1.0.0"
