[package]
name = "evcxr_repl"
version = "0.7.0"
license = "Apache-2.0"
description = "A REPL for Rust"
repository = "https://github.com/google/evcxr"
readme = "README.md"
authors = ["The Evcxr Authors"]
edition = "2018"

[dependencies]
evcxr = { version = "=0.7.0", path = "../evcxr" }
rustyline = "6.3.0"
colored = "2.0.0"
lazy_static = "1.4.0"
regex = { version = "1.4.1", default-features = false, features = [ "std" ] }
structopt = "0.3"
unicode-xid = "0.2"
