[package]
name = "evcxr_repl"
version = "0.5.3"
license = "Apache-2.0"
description = "A REPL for Rust"
repository = "https://github.com/google/evcxr"
readme = "README.md"
authors = [
    "David Lattimore <dvdlttmr@gmail.com>",
    "Diogo Sousa <diogogsousa@gmail.com>",
]
edition = "2018"

[dependencies]
evcxr = { version = "=0.5.3", path = "../evcxr" }
rustyline = "6.0.0"
colored = "1.9.3"
lazy_static = "1.3.0"
regex = { version = "1.3.1", default-features = false, features = [ "std" ] }
structopt = "0.3"
unicode-xid = "0.2"
